version: '2'
services:
  messagecloud_jasmin:
     image: messagecloud/jasmin:latest
     restart: always
     ports:
         - "2775:2775"
         - "${JASMIN_PORT}:${JASMIN_PORT}"
         - "1401:1401"
         - "8000:8000"
         - "8001:8001"
     volumes:
         - jasmin-store:/etc/jasmin/store
         - jasmin-logs:/var/log/jasmin
     networks:
       jasmin-network:
         ipv4_address: 172.20.0.1
     build:
         context: ..
         dockerfile: /docker/Dockerfile-HA-RabbitMQ
         args:
           JASMIN_VERSION: "${JASMIN_VERSION}"
           JASMIN_USERNAME: "${JASMIN_USERNAME}"
           JASMIN_PASSWORD: "${JASMIN_PASSWORD}"
           JASMIN_PASSWORD_MD5: "${JASMIN_PASSWORD_MD5}"
           JASMIN_PORT: "${JASMIN_PORT}"
           RABBITMQ_USERNAME: "${RABBITMQ_USERNAME}"
           RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
           RABBITMQ_HOST: "${RABBITMQ_HOST}"
           RABBITMQ_VHOST: "${RABBITMQ_VHOST}"
           JASMIN_API_USERNAME: "${JASMIN_API_USERNAME}"
           JASMIN_API_PASSWORD: "${JASMIN_API_PASSWORD}"
           JASMIN_WEBUI_USERNAME: "${JASMIN_WEBUI_USERNAME}"
           JASMIN_WEBUI_PASSWORD: "${JASMIN_WEBUI_PASSWORD}"
     environment:
         JASMIN_HOST: "${JASMIN_HOST}"
         JASMIN_PORT: "${JASMIN_PORT}"
         JASMIN_USERNAME: "${JASMIN_USERNAME}"
         JASMIN_PASSWORD: "${JASMIN_PASSWORD}"
         RABBITMQ_USERNAME: "${RABBITMQ_USERNAME}"
         RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  messagecloud_redis:
     image: redis:latest
     restart: always
     ports:
         - "6379:6379"
     entrypoint: redis-server /usr/local/etc/redis/redis.conf
     volumes:
         - ./redis.conf:/usr/local/etc/redis/redis.conf
         - redis-data:/data
         - redis-logs:/var/log/redis
     networks:
       jasmin-network:
         ipv4_address: 172.20.0.2
volumes:
  jasmin-store:
  jasmin-logs:
  redis-data:
  redis-logs:
networks:
  jasmin-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
          ip_range: 172.20.0.0/24
          gateway: 172.20.0.254
